name: catholic_liturgy
description: Catholic LIturgy
version: 0.0.2
homepage: https://github.com/flavio20002/Catholic-Liturgy-Dart

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  enum_to_string: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  csv: ^5.0.1

flutter:
