import '../catholic_liturgy.dart';

Map<String, LiturgyEnum> ferialFixedLiturgy = {
  '25/01': LiturgyEnum.theConversionOfSaintPaulTheApostle,
  '26/01': LiturgyEnum.saintsTimothyAndTitusBishops,
  '14/02': LiturgyEnum.saintsCyrilAndMethodius,
  '22/02': LiturgyEnum.theChairOfSaintPeterTheApostle,
  '25/04': LiturgyEnum.saintMarkEvangelist,
  '29/04': LiturgyEnum.saintCatherineOfSiena,
  '01/05': LiturgyEnum.saintJosephTheWorker,
  '02/05': LiturgyEnum.saintAthanasius,
  '03/05': LiturgyEnum.saintsPhilipAndJamesApostles,
  '14/05': LiturgyEnum.saintMatthiasApostle,
  '31/05': LiturgyEnum.theVisitationOfTheBlessedVirginMary,
  '11/06': LiturgyEnum.saintBarnabasApostle,
  '13/06': LiturgyEnum.saintAnthonyOfPadua,
  '03/07': LiturgyEnum.saintThomasApostle,
  '11/07': LiturgyEnum.saintBenedictAbbot,
  '22/07': LiturgyEnum.saintMaryMagdalene,
  '23/07': LiturgyEnum.saintBridget,
  '25/07': LiturgyEnum.saintJamesApostle,
  '29/07': LiturgyEnum.saintMartha,
  '09/08': LiturgyEnum.saintTeresaBenedictaOfTheCross,
  '10/08': LiturgyEnum.saintLawrencer,
  '24/08': LiturgyEnum.saintBartholomewApostle,
  '29/08': LiturgyEnum.thePassionOfSaintJohnTheBaptist,
  '08/09': LiturgyEnum.theNativityOfTheBlessedVirginMary,
  '15/09': LiturgyEnum.ourLadyOfSorrows,
  '21/09': LiturgyEnum.saintMatthewApostleAndEvangelist,
  '29/09': LiturgyEnum.saintsMichaelGabrielAndRaphaelArchangels,
  '02/10': LiturgyEnum.theHolyGuardianAngels,
  '04/10': LiturgyEnum.saintFrancisOfAssisi,
  '18/10': LiturgyEnum.saintLukeEvangelist,
  '28/10': LiturgyEnum.saintsSimonAndJudeApostles,
  '21/11': LiturgyEnum.thePresentationOfTheBlessedVirginMary,
  '30/11': LiturgyEnum.saintAndrewApostle,
  '17/12': LiturgyEnum.adventWeekDay17December,
  '18/12': LiturgyEnum.adventWeekDay18December,
  '19/12': LiturgyEnum.adventWeekDay19December,
  '20/12': LiturgyEnum.adventWeekDay20December,
  '21/12': LiturgyEnum.adventWeekDay21December,
  '22/12': LiturgyEnum.adventWeekDay22December,
  '23/12': LiturgyEnum.adventWeekDay23December,
  '24/12': LiturgyEnum.adventWeekDay24December,
  '26/12': LiturgyEnum.saintStephenTheFirstMartyr,
  '27/12': LiturgyEnum.saintJohnApostleAndEvangelist,
  '28/12': LiturgyEnum.theHolyInnocentsMartyrs,
  '29/12': LiturgyEnum.fifthDayWithinOctaveOfNativity,
  '30/12': LiturgyEnum.sixthDayWithinOctaveOfNativity,
  '31/12': LiturgyEnum.seventhDayWithinOctaveOfNativity,
};

Map<String, LiturgyEnum> feastFixedLiturgy = {
  '01/01': LiturgyEnum.maryHolyMotherOfGod,
  '02/02': LiturgyEnum.thePresentationOfTheLord,
  '24/06': LiturgyEnum.theNativityOfSaintJohnTheBaptist,
  '29/06': LiturgyEnum.saintsPeterAndPaul,
  '06/08': LiturgyEnum.theTransfigurationOfTheLord,
  '15/08': LiturgyEnum.theAssumptionOfTheBlessedVirginMary,
  '14/09': LiturgyEnum.theExaltationOfTheHolyCross,
  '01/11': LiturgyEnum.allSaints,
  '02/11': LiturgyEnum.theCommemorationOfAllTheFaithfulDeparted,
  '09/11': LiturgyEnum.theDedicationOfTheLateranBasilica,
  '25/12': LiturgyEnum.christmas,
};

Map<String, FranciscanFeastMemoryEnum> franciscanFeastMemoryFixed = {
  '24/05':
      FranciscanFeastMemoryEnum.dedicazioneDellaBasilicaDiSanFrancescoInAssisi,
  '15/07': FranciscanFeastMemoryEnum.sanBonaventuraVescovoEDottoreDellaChiesa,
  '11/08': FranciscanFeastMemoryEnum
      .santaMadreChiaraVergineCofondatriceDelIIOrdineFrancescano,
  '14/08':
      FranciscanFeastMemoryEnum.sanMassimilianoMariaKolbePresbiteroEMartire,
  '02/08': FranciscanFeastMemoryEnum
      .santaMariaDegliAngeliAllaPorziuncolaPerdonDAssisi,
  '08/08': FranciscanFeastMemoryEnum.sanDomenicoPresbitero,
  '17/09': FranciscanFeastMemoryEnum.impressioneDelleStimmateDiSanFrancesco,
  '18/09': FranciscanFeastMemoryEnum.sanGiuseppeDaCopertinoPresbitero,
  '16/01': FranciscanFeastMemoryEnum
      .santiBerardoECompagniProtomartiriDellOrdineFrancescano,
  '30/01': FranciscanFeastMemoryEnum.santaGiacintaMariscottiVergine,
  '03/01': FranciscanFeastMemoryEnum.santissimoNomediGesu,
  '23/10': FranciscanFeastMemoryEnum.sanGiovanniDaCapestranoPresbitero,
  '14/11': FranciscanFeastMemoryEnum.sanNicolaTavelicPresbiteroECompagniMartiri,
  '26/11': FranciscanFeastMemoryEnum.sanLeonardoDaPortoMaurizioPresbitero,
  '27/11': FranciscanFeastMemoryEnum.sanFrancescoAntonioFasaniPresbitero,
  '06/02': FranciscanFeastMemoryEnum
      .ssPietroBattistaPaoloMikiECompagniProtomartiriDelGiappone,
  '07/08': FranciscanFeastMemoryEnum.sColetaDaCorbieVergine,
  '24/04': FranciscanFeastMemoryEnum.sFedeleDaSigmaringenSacerdoteEMartire,
  '12/05': FranciscanFeastMemoryEnum.sanLeopoldoMandicDaCastelnuovoPresbitero,
  '16/05': FranciscanFeastMemoryEnum.santaMargheritaDaCortonaPenitente,
  '17/05': FranciscanFeastMemoryEnum.sanPasqualeBaylonReligioso,
  '18/05': FranciscanFeastMemoryEnum.sanFeliceDaCantaliceReligioso,
  '20/05': FranciscanFeastMemoryEnum.sanBernardinoDaSienaPresbitero,
  '10/07': FranciscanFeastMemoryEnum.santaVeronicaGiulianiVergine,
  '21/07': FranciscanFeastMemoryEnum
      .sanLorenzoDaBrindisiPresbiteroEDottoreDellaChiesa,
  '25/08': FranciscanFeastMemoryEnum
      .sanLudovicoIXRePatronoDelOrdineFrancescanoSecolare,
};
