import '../catholic_liturgy.dart';

Map<String, LiturgyEnum> ferialFixedLiturgy = {
  '25/01': LiturgyEnum.theConversionOfSaintPaulTheApostle,
  '26/01': LiturgyEnum.saintsTimothyAndTitusBishops,
  '14/02': LiturgyEnum.saintsCyrilAndMethodius,
  '22/02': LiturgyEnum.theChairOfSaintPeterTheApostle,
  '25/04': LiturgyEnum.saintMarkEvangelist,
  '29/04': LiturgyEnum.saintCatherineOfSiena,
  '01/05': LiturgyEnum.saintJosephTheWorker,
  '02/05': LiturgyEnum.saintAthanasius,
  '03/05': LiturgyEnum.saintsPhilipAndJamesApostles,
  '14/05': LiturgyEnum.saintMatthiasApostle,
  '31/05': LiturgyEnum.theVisitationOfTheBlessedVirginMary,
  '11/06': LiturgyEnum.saintBarnabasApostle,
  '03/07': LiturgyEnum.saintThomasApostle,
  '11/07': LiturgyEnum.saintBenedictAbbot,
  '22/07': LiturgyEnum.saintMaryMagdalene,
  '23/07': LiturgyEnum.saintBridget,
  '25/07': LiturgyEnum.saintJamesApostle,
  '29/07': LiturgyEnum.saintMartha,
  '09/08': LiturgyEnum.saintTeresaBenedictaOfTheCross,
  '10/08': LiturgyEnum.saintLawrencer,
  '24/08': LiturgyEnum.saintBartholomewApostle,
  '29/08': LiturgyEnum.thePassionOfSaintJohnTheBaptist,
  '08/09': LiturgyEnum.theNativityOfTheBlessedVirginMary,
  '15/09': LiturgyEnum.ourLadyOfSorrows,
  '21/09': LiturgyEnum.saintMatthewApostleAndEvangelist,
  '29/09': LiturgyEnum.saintsMichaelGabrielAndRaphaelArchangels,
  '02/10': LiturgyEnum.theHolyGuardianAngels,
  '04/10': LiturgyEnum.saintFrancisOfAssisi,
  '18/10': LiturgyEnum.saintLukeEvangelist,
  '28/10': LiturgyEnum.saintsSimonAndJudeApostles,
  '21/11': LiturgyEnum.thePresentationOfTheBlessedVirginMary,
  '30/11': LiturgyEnum.saintAndrewApostle,
  '17/12': LiturgyEnum.adventWeekDay17December,
  '18/12': LiturgyEnum.adventWeekDay18December,
  '19/12': LiturgyEnum.adventWeekDay19December,
  '20/12': LiturgyEnum.adventWeekDay20December,
  '21/12': LiturgyEnum.adventWeekDay21December,
  '22/12': LiturgyEnum.adventWeekDay22December,
  '23/12': LiturgyEnum.adventWeekDay23December,
  '24/12': LiturgyEnum.adventWeekDay24December,
  '26/12': LiturgyEnum.saintStephenTheFirstMartyr,
  '27/12': LiturgyEnum.saintJohnApostleAndEvangelist,
  '28/12': LiturgyEnum.theHolyInnocentsMartyrs,
  '29/12': LiturgyEnum.fifthDayWithinOctaveOfNativity,
  '30/12': LiturgyEnum.sixthDayWithinOctaveOfNativity,
  '31/12': LiturgyEnum.seventhDayWithinOctaveOfNativity,
};

Map<String, LiturgyEnum> feastFixedLiturgy = {
  '01/01': LiturgyEnum.maryHolyMotherOfGod,
  '02/02': LiturgyEnum.thePresentationOfTheLord,
  '24/06': LiturgyEnum.theNativityOfSaintJohnTheBaptist,
  '29/06': LiturgyEnum.saintsPeterAndPaul,
  '06/08': LiturgyEnum.theTransfigurationOfTheLord,
  '15/08': LiturgyEnum.theAssumptionOfTheBlessedVirginMary,
  '14/09': LiturgyEnum.theExaltationOfTheHolyCross,
  '01/11': LiturgyEnum.allSaints,
  '02/11': LiturgyEnum.theCommemorationOfAllTheFaithfulDeparted,
  '09/11': LiturgyEnum.theDedicationOfTheLateranBasilica,
  '25/12': LiturgyEnum.christmas,
};

Map<String, FranciscanFeastMemoryEnum> franciscanFeastMemoryFixed = {
  '24/05':
      FranciscanFeastMemoryEnum.dedicazioneDellaBasilicaDiSanFrancescoInAssisi,
  '15/07': FranciscanFeastMemoryEnum.sanBonaventuraVescovoEDottoreDellaChiesa,
  '11/08': FranciscanFeastMemoryEnum
      .santaMadreChiaraVergineCofondatriceDelIIOrdineFrancescano,
  '14/08':
      FranciscanFeastMemoryEnum.sanMassimilianoMariaKolbePresbiteroEMartire,
  '02/08': FranciscanFeastMemoryEnum
      .santaMariaDegliAngeliAllaPorziuncolaPerdonDAssisi,
  '08/08': FranciscanFeastMemoryEnum.sanDomenicoPresbitero,
  '17/09': FranciscanFeastMemoryEnum.impressioneDelleStimmateDiSanFrancesco,
  '18/09': FranciscanFeastMemoryEnum.sanGiuseppeDaCopertinoPresbitero,
  '16/01': FranciscanFeastMemoryEnum
      .santiBerardoECompagniProtomartiriDellOrdineFrancescano,
  '30/01': FranciscanFeastMemoryEnum.santaGiacintaMariscottiVergine,
  '03/01': FranciscanFeastMemoryEnum.santissimoNomediGesu,
  '23/10': FranciscanFeastMemoryEnum.sanGiovanniDaCapestranoPresbitero,
  '14/11': FranciscanFeastMemoryEnum.sanNicolaTavelicPresbiteroECompagniMartiri,
  '26/11': FranciscanFeastMemoryEnum.sanLeonardoDaPortoMaurizioPresbitero,
  '27/11': FranciscanFeastMemoryEnum.sanFrancescoAntonioFasaniPresbitero,
  '06/02': FranciscanFeastMemoryEnum
      .ssPietroBattistaPaoloMikiECompagniProtomartiriDelGiappone,
  '07/08': FranciscanFeastMemoryEnum.sColetaDaCorbieVergine,
  '24/04': FranciscanFeastMemoryEnum.sFedeleDaSigmaringenSacerdoteEMartire,
  '12/05': FranciscanFeastMemoryEnum.sanLeopoldoMandicDaCastelnuovoPresbitero,
  '16/05': FranciscanFeastMemoryEnum.santaMargheritaDaCortonaPenitente,
  '17/05': FranciscanFeastMemoryEnum.sanPasqualeBaylonReligioso,
  '18/05': FranciscanFeastMemoryEnum.sanFeliceDaCantaliceReligioso,
  '20/05': FranciscanFeastMemoryEnum.sanBernardinoDaSienaPresbitero,
  '10/07': FranciscanFeastMemoryEnum.santaVeronicaGiulianiVergine,
  '21/07': FranciscanFeastMemoryEnum
      .sanLorenzoDaBrindisiPresbiteroEDottoreDellaChiesa,
  '25/08': FranciscanFeastMemoryEnum
      .sanLudovicoIXRePatronoDelOrdineFrancescanoSecolare,
};

Map<String, SaintMemoryEnum> saintsMemoryFixed = {
  '17/01': SaintMemoryEnum.santantonioAbate,
  '02/01': SaintMemoryEnum
      .santiBasilioMagnoEGregorioNazianzenoVescoviEDottoriDellaChiesa,
  '21/01': SaintMemoryEnum.santagneseVergineEMartire,
  '24/01': SaintMemoryEnum.sanFrancescoDiSalesVescovoEDottoreDellaChiesa,
  '26/01': SaintMemoryEnum.santiTimoteoETitoVescovi,
  '28/01': SaintMemoryEnum.sanTommasoDAquinoPresbiteroEDottoreDellaChiesa,
  '31/01': SaintMemoryEnum.sanGiovanniBoscoPresbitero,
  '01/10': SaintMemoryEnum
      .santaTeresaDiGesuBambinodiLisieuxVergineEDottoreDellaChiesa,
  '15/10': SaintMemoryEnum.santaTeresaDiGesudAvilaVergineEDottoreDellaChiesa,
  '17/10': SaintMemoryEnum.santignazioDiAntiochiaVescovoEMartire,
  '02/10': SaintMemoryEnum.santiAngeliCustodi,
  '07/10': SaintMemoryEnum.beataMariaVergineDelRosario,
  '10/11': SaintMemoryEnum.sanLeoneMagnoPapaEDottoreDellaChiesa,
  '11/11': SaintMemoryEnum.sanMartinoDiToursVescovo,
  '12/11': SaintMemoryEnum.sanGiosafatVescovoEMartire,
  '17/11': SaintMemoryEnum.santaElisabettaDUngheria,
  '21/11': SaintMemoryEnum.presentazioneDellaBeataVergineMariaAlTempio,
  '22/11': SaintMemoryEnum.santaCeciliaVergineEMartire,
  '24/11': SaintMemoryEnum.santiAndreaDungLacPresbiteroECompagniMartiri,
  '04/11': SaintMemoryEnum.sanCarloBorromeoVescovo,
  '13/12': SaintMemoryEnum.santaLuciaVergineEMartire,
  '14/12': SaintMemoryEnum.sanGiovanniDellaCrocePresbiteroEDottoreDellaChiesa,
  '03/12': SaintMemoryEnum.sanFrancescoSaverioPresbitero,
  '06/12': SaintMemoryEnum.sanNicolaVescovo,
  '07/12': SaintMemoryEnum.santambrogioVescovoEDottoreDellaChiesa,
  '10/02': SaintMemoryEnum.santaScolasticaVergine,
  '23/02': SaintMemoryEnum.sanPolicarpoVescovoEMartire,
  '05/02': SaintMemoryEnum.santagataVergineEMartire,
  '6/02': SaintMemoryEnum.sanPaoloMikiECompagniMartiri,
  '07/03': SaintMemoryEnum.santePerpetuaEFelicitaMartiri,
  '11/04': SaintMemoryEnum.santoStanislaoVescovoEMartire,
  '07/04': SaintMemoryEnum.sanGiovanniBattistaDeLaSallePresbitero,
  '01/05': SaintMemoryEnum.sanGiuseppeLavoratore,
  '02/05': SaintMemoryEnum.santatanasioVescovoEDottoreDellaChiesa,
  '26/05': SaintMemoryEnum.sanFilippoNeriPresbitero,
  '01/06': SaintMemoryEnum.sanGiustinoMartire,
  '11/06': SaintMemoryEnum.sanBarnabaApostolo,
  '13/06': SaintMemoryEnum.sAntonioDiPadovaPresbiteroEDottoreDellaChiesa,
  '21/06': SaintMemoryEnum.sanLuigiGonzagaReligioso,
  '28/06': SaintMemoryEnum.santireneoVescovoEMartire,
  '03/06': SaintMemoryEnum.sanCarloLwangaECompagniMartiri,
  '05/06': SaintMemoryEnum.sanBonifacioVescovoEMartire,
  '15/07': SaintMemoryEnum.sanBonaventuraVescovoEDottoreDellaChiesa,
  '26/07': SaintMemoryEnum.santiGioacchinoEAnnaGenitoriDellaBeataVergineMaria,
  '29/07': SaintMemoryEnum.santaMartaConMariaELazzaro,
  '31/07': SaintMemoryEnum.santignazioDiLoyolaPresbiteroFondatoreDeiGesuiti,
  '01/08': SaintMemoryEnum.santalfonsoMariaDeLiguoriVescovoEDottoreDellaChiesa,
  '11/08': SaintMemoryEnum.santaChiaraVergine,
  '14/08': SaintMemoryEnum.sanMassimilianoMariaKolbePresbiteroEMartire,
  '20/08': SaintMemoryEnum.sanBernardoAbateEDottoreDellaChiesa,
  '21/08': SaintMemoryEnum.sanPioXPapa,
  '22/08': SaintMemoryEnum.beataVergineMariaRegina,
  '27/08': SaintMemoryEnum.santaMonica,
  '28/08': SaintMemoryEnum.santagostinoVescovoEDottoreDellaChiesa,
  '29/08': SaintMemoryEnum.martirioDiSanGiovanniBattista,
  '04/08': SaintMemoryEnum.sanGiovanniMariaVianneyPresbitero,
  '8/08': SaintMemoryEnum.sanDomenicoPresbitero,
  '13/09': SaintMemoryEnum.sanGiovanniCrisostomoVescovoEDottoreDellaChiesa,
  '15/09': SaintMemoryEnum.beataVergineMariaAddolorata,
  '16/09': SaintMemoryEnum.santiCornelioPapaECiprianoVescovoMartiri,
  '20/09': SaintMemoryEnum
      .santiAndreaKimTaegonPresbiteroPaoloChongHasangECompagniMartiri,
  '23/09': SaintMemoryEnum.sanPioDaPietrelcinaPresbitero,
  '27/09': SaintMemoryEnum.sanVincenzoDePaoliPresbitero,
  '03/09': SaintMemoryEnum.sanGregorioMagnoPapaEDottoreDellaChiesa,
  '30/09': SaintMemoryEnum.sanGirolamoPresbiteroEDottoreDellaChiesa,
};

Map<String, FacultativeSaintMemoryEnum> facultativeSaintsMemoryFixed = {
  '11/10': FacultativeSaintMemoryEnum.sanGiovanniXXIIIPapa,
  '22/10': FacultativeSaintMemoryEnum.sanGiovanniPaoloIIPapa,
  '11/02': FacultativeSaintMemoryEnum.beataVergineMariaDiLourdes,
  '13/05': FacultativeSaintMemoryEnum.beataVergineMariaDiFatima,
  '16/07': FacultativeSaintMemoryEnum.beataVergineMariaDelMonteCarmelo,
};
